package com.MissJEnterprises.cars.models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name="cars")
public class Car {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
		//descriptors for the object, fields added to the mySQL database
	private Long id;
	@Size(min=1, max=30, message="That make size is too small or too big") //validation 
	private String make;
	@Size(min=1, max=30)
	private String model;
	@NotNull
	private int year;
	@Size(min=1, max=30)
	private String color;
			//@NotEmpty //Valid as long as something is there, but will accept spaces
	@NotBlank  // valid as long as something is there, but trims out spaces
	private String transmission;
	@Column(updatable=false)  //have a date for when it was created, can't be updated
	@DateTimeFormat(pattern = "YYYY-MM-dd HH:mm:ss")
	private Date createdAt;
	@DateTimeFormat(pattern = "YYYY-MM-dd HH:mm:ss")
	private Date updatedAt;
	@PrePersist	//creates before anything else touches the date
	protected void onCreate() {
		this.createdAt = new Date();
	}
	@PreUpdate	//updates before anything else touches the date
	protected void onUpdate() {
		this.updatedAt = new Date();
	}
	
	
	
		//constructor, POJO with an empty object
	public Car() {

	}
	
		public Car(String make,  String model, String color, int year, String transmission) {
			this.make = make;
			this.model = model;
			this.year = year;
			this.color = color;
			this.transmission = transmission;
		}
		//new constructor for creating a car
	
	
	
		//getters and setters, auto generated by STS
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getMake() {
		return make;
	}

	public void setMake(String make) {
		this.make = make;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getTransmission() {
		return transmission;
	}
	public void setTransmission(String transmission) {
		this.transmission = transmission;
	}
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	
	
	
}
